### ISSUE TITLE
Add option to search for subtitles

### ISSUE THREAD

**Issue by MizzleDK** [MizzleDK/Mizuu#265]
<a href="https://github.com/MizzleDK"><img src="https://avatars.githubusercontent.com/u/1175953?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MizzleDK](https://github.com/MizzleDK)**
_Wednesday Nov 06, 2013 at 01:09 GMT_
_Originally opened as https://github.com/MizzleDK/MizuuApp/issues/11_

----

Should support at least one of the major subtitle sites, i.e. subscene, podnapisi or opensubtitles.

**Comment by spear1403** [comment]
I'm waiting for this one for quite some time now. Is it still on the to-do list?

**Comment by MizzleDK** [comment]
There's like 80 suggestions on GitHub and even more in my email inbox. I simply don't have time to do everything at once, and this one in particular has never been of high priority. The main reason being that it'd be an overly complicated user flow. Ideally, this should be available from within a video player, where you can immediately see if the selected subtitles match.

If anyone wants to do it, by all means feel free.
