### ISSUE TITLE
Improve the experience on non-touch devices

### ISSUE THREAD

**Issue by MizzleDK** [MizzleDK/Mizuu#276]
<a href="https://github.com/MizzleDK"><img src="https://avatars.githubusercontent.com/u/1175953?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MizzleDK](https://github.com/MizzleDK)**
_Wednesday Nov 06, 2013 at 01:11 GMT_
_Originally opened as https://github.com/MizzleDK/MizuuApp/issues/22_

----

**Comment by Black6spdZ** [comment]
I'm using a Fire TV remote and almost everything works except when I press the PLAY button, it doesn't play.. instead I have to blindly cursor over the play icon and press ok
