### ISSUE TITLE
Kid mode

### ISSUE THREAD

**Issue by MizzleDK** [MizzleDK/Mizuu#398]
<a href="https://github.com/MizzleDK"><img src="https://avatars.githubusercontent.com/u/1175953?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MizzleDK](https://github.com/MizzleDK)**
_Saturday Apr 19, 2014 at 20:16 GMT_
_Originally opened as https://github.com/MizzleDK/MizuuApp/issues/144_

----

Lots of stuff could be disabled in a "kid mode". Also, movies could start immediately when pressing something from the movie overview.

**Comment by ajford** [comment]
This would be be fantastic!  Even if you had the "kids mode" as a paid option, I'd gladly pay for it. 

I would also suggest simplifying the TV Shows section, where you go directly to the seasons list or episode list when you click a show.

Unifying (or providing the option to unify) the TV Shows and Movies would also be useful.

There's no good media center/media player app for kids with the features that Mizuu has.
