### ISSUE TITLE
Apply sorting preference to every view

### ISSUE THREAD

**Issue by KlaasJanV** [MizzleDK/Mizuu#482]
Hi Michell, I noticed after this morning's update, the 'all movies' view remembers the preferred sorting (thanks :-)). But I also noticed this only works in 'All movies'. When from 'Unwatched' you scroll 2 views sideways  and back to Unwatched (for instance), Mizuu has forgotten the sorting (let alone after closing the app). In previous versions the chosen sorting would apply to/through all views (so also 'watched, unwatched, favorites etc). That worked fine, so no need to remember 'per view' but it would be nice if the sorting would be remembered througout the app (and after closing the app, which now works for 'All movies', but I already said that :-)).

**Comment by MizzleDK** [comment]
Tabs will be removed in the version I'm working on, so closing this.

**Comment by KlaasJanV** [comment]
Quietly working on Mizuu again? #hush-hush# :-)

**Comment by MizzleDK** [comment]
:-)
