### ISSUE TITLE
Add swipe to refresh for online movies and web videos

### ISSUE THREAD

**Issue by MizzleDK** [MizzleDK/Mizuu#494]
A menu item in the overflow menu should be added as well.

**Comment by eyedol** [comment]
@MizzleDK  still a valid issue?

**Comment by MizzleDK** [comment]
Sure thing! It shouldn't be much of an issue to do, if you're thinking about doing it :-)

**Comment by eyedol** [comment]
Yup. Will find time to stab it. Thanks!

**Comment by MizzleDK** [comment]
Online movies and web videos will be removed, so closing this.
