### ISSUE TITLE
Ability to point Mizuu to server

### ISSUE THREAD

**Issue by afinite** [MizzleDK/Mizuu#496]
Would be awesome if I could connect the app to my own web server and it would scan and play files (stream) from there.

**Comment by MizzleDK** [comment]
Sure! Keep an eye on the site. I'll have to do some refactoring of the code in order to make it work, like I said in the previous post, but after that, it should hopefully be fairly easy to implement.

**Comment by MizzleDK** [comment]
Closing this for now
