### ISSUE TITLE
Publish to Kindle AppStore

### ISSUE THREAD

**Issue by irishpadres** [MizzleDK/Mizuu#497]
It's a great app and I was able to sideload it on to my Kindle Fire but it'd be easier if it was published to the AppStore like Google Play.

**Comment by MizzleDK** [comment]
I don't really have any good experience with Amazon's app store. I might reconsider it, as I believe I still have my account there, but I'll have to see how much time I have on my hands for supporting two app stores.

All the publicity regarding v3.0 has really come as a surprise to me. I've literally had 400+ inquiries in the last few days.

**Comment by platanoverde** [comment]
This is an awesome app and I use it to make it easy for my kids to pick movies from a smb share. I would also like to see the app published to the Amazon App store. 

My kids have a Fire HD Kids edition which utilizes FreeTime Unlimited to ensure they only have access to age appropriate media.  However, FreeTime does not allow access to sideloaded apps. That means that I have to sign them out of FreeTime and sign into my profile to let them use Mizuu.

It would make things so much easier if I could just install Mizuu from the Amazon Appstore. That would allow them to have access directly from within FreeTime Unlimited.
Thank You.

**Comment by MizzleDK** [comment]
Hi!

My answer above still stands. I don't have time to manage it at the moment. It's almost been weeks since I had time to do anything related to Mizuu other than just answer emails and stuff like that.

**Comment by platanoverde** [comment]
I have a developer account on Amazon, so I can publish the app there for you. Would it appropriate to use the Mizuu apk from the download section or should I fork the code and then publish a new apk?

**Comment by MizzleDK** [comment]
Fork the code and publish a new one under another package name.
Den 03/03/2015 21.25 skrev "platanoverde" <notifications@github.com>:

**Comment by platanoverde** [comment]
Great! I have my own API keys for everything except "mizuu_filename_key". Can you provide me with a key?

**Comment by MizzleDK** [comment]
You can just remove the code that references that key. It's less than 50 lines as far as I remember, so it's not a lot.

**Comment by platanoverde** [comment]
It's now available in the Amazon App store as Sofoli.

http://www.amazon.com/LoMax-Tech-Sofoli/dp/B00U0W7Z5G/ref=sr_1_1?ie=UTF8&qid=1429371379&sr=8-1&keywords=sofoli

This gives my kids the ability to use the app on their Kindle Fire since "Free Time" accounts don't allow sideloaded apps.

**Comment by irishpadres** [comment]
Thanks!
