### ISSUE TITLE
use smb poster / backdrop

### ISSUE THREAD

**Issue by srirams** [MizzleDK/Mizuu#498]
I have all my artwork stored locally (smb) and would rather like to use those. Is this possible? I took a quick look at the source but am not sure how the caching works (in addition the locally stored artwork is in a higher res and would probably need to be down scaled before caching...)

**Comment by MizzleDK** [comment]
It already works with custom cover art and backdrop images via SMB. You just have to enable it in the settings and make sure that your files follow the supported naming convention:
https://github.com/MizzleDK/Mizuu/wiki/Custom-movie-data

It only works for movies, though.

**Comment by srirams** [comment]
It doesn't seem to be working for me.

In SmbMovie.java:

    addNfoFile(MizLib.removeExtension(file.getCanonicalPath()), file.getInputStream());

While in MovieIdentification.java

                String nfo1 = ms.getFilepath().replaceAll("part[1-9]|cd[1-9]", "").trim();
                String nfo2 = MizLib.convertToGenericNfo(ms.getFilepath());

                if (mNfoFiles.containsKey(nfo1)) {
                    new NfoMovie(ms.getFilepath(), mNfoFiles.get(nfo1), mContext, mCallback, mCount);
                } else if (mNfoFiles.containsKey(nfo2)) {
                    new NfoMovie(ms.getFilepath(), mNfoFiles.get(nfo2), mContext, mCallback, mCount);
                } else {
                    match = false;
                }

So I don't think the .nfo files will ever match (unless I'm missing something).

**Comment by MizzleDK** [comment]
The NFO file code is unrelated to the code that handles custom cover art :-)

**Comment by srirams** [comment]
I can't seem to get that to work either. I have a folder.jpg in the movie folder in the correct size and ratio, but it's not used.

I can't seem to find the code path for getting the image either.

**Comment by MizzleDK** [comment]
The code is available here:
https://github.com/MizzleDK/Mizuu/blob/master/app/src/main/java/com/miz/functions/OkHttpDownloader.java

There might be a caching issue, though. If it's already loaded the local picture once, it might just ignore the one on your SMB share despite the setting for custom movie data being enabled. It's something I'll fix in a future release, but I'm awaiting an update for the image loading library that Mizuu uses.

**Comment by srirams** [comment]
found the problem:

    s = MizLib.getCustomCoverArt(filename, MizLib.getAuthFromFilepath(MizLib.TYPE_MOVIE, imageUri), MizLib.COVER);

should be:

    s = MizLib.getCustomCoverArt(filename, MizLib.getAuthFromFilepath(MizLib.TYPE_MOVIE, filename), MizLib.COVER);

**Comment by MizzleDK** [comment]
Oh yeah, good eye! I'll test it when I can and fix it for the next minor release. Thanks for letting me know :-)
