### ISSUE TITLE
Add specific filter per file source entry instead of per content type

### ISSUE THREAD

**Issue by jcdeoferio** [MizzleDK/Mizuu#503]
The current filters for File Sources are:
- SMB network share
- On Device
- DLNA/UPnP

It's better to have a filter per file source added. For example, if you have 2 file sources: Anime and American Shows. You should be able to filter only the Anime Shows.

**Comment by MizzleDK** [comment]
Agreed, but it's impossible to do with UPnP files. Or rather, it's
impossible to do it in a sane way.

**Comment by jcdeoferio** [comment]
I think it's possible to simplify by adding a reference to the sources table in the tvshows and movie tables?

Haven't read through your code that much, just checking from the database side.

**Comment by MizzleDK** [comment]
It is, but the database schema needs to be changed for movie filepaths and TV show filepaths. Each should include a reference to the ID of the UPnP folder.

Also, it's a breaking change, meaning that people can't just upgrade and expect everything to work. They'll have to re-update their library again.

**Comment by jcdeoferio** [comment]
How about, making the filters only available once the libraries has been updated?

**Comment by MizzleDK** [comment]
Yeah, might do that. It's still a pretty large change, though.
