### ISSUE TITLE
I had to check Mizuu's github page after visiting the official site to understand what it is

### ISSUE THREAD

**Issue by zeroum** [MizzleDK/Mizuu#526]
I found the official site really confusing, I've read all the paragraphs and I still was at a loss about what Mizuu was about. Lots of beautiful pictures, but not much information.

"Is it related to PopcornTime?", "Does it download movies?" "Is it an integrated interface to all my VoD services?" Those were my thoughts.

To me it looked like you wanted to keep it ambiguous on purpose, like malicious marketing people do when they want to sell products which aren't that great.

Only when I went to https://github.com/MizzleDK/Mizuu I finally understood, with very concise words, what the app was:

> Mizuu - media indexer for Android

> Mizuu is a user friendly media center application for Android tablets and smartphones running Android 4.0.3 (API level 15) or newer. The application helps manage all your movie and TV show video files - and automatically fetches useful information about the video content, including title, plot, cover art and actors.

Now that sounds like something helpful. Something I'd download. A good natured app.

**Comment by MizzleDK** [comment]
I've updated the text in the first "area" a bit. Not quite sure what could be done other than that.

**Comment by zeroum** [comment]
I'm not sure either :)

Thank you!
