### ISSUE TITLE
Add the translator's list.

### ISSUE THREAD

**Issue by pexcn** [MizzleDK/Mizuu#527]
I hope this application will be add "The translator's list", because it can give translator a sense of accomplishment.

**Comment by pexcn** [comment]
:grin:

**Comment by MizzleDK** [comment]
Hi!

It'll likely be a mess maintaining it. The app currently links to GitHub,
where people will be able to see contributions and thereby translations.

Cheers
Michell

**Comment by pexcn** [comment]
OK, thanks!
