### ISSUE TITLE
Support for a custom video service on a web server

### ISSUE THREAD

**Issue by da1nonly** [MizzleDK/Mizuu#529]
Hi is it possible to load tv / movies information and video from remote source like json url, i have a video service that i would love to load the content in mizuu.

**Comment by MizzleDK** [comment]
A video service?

**Comment by da1nonly** [comment]
i got a wordpress site with a bunch of videos already grouped by playlists and tags etc, wanted a way to view them on a android device. just wanted to know if it was possible to load the content via json , so that i could create a json api for mizuu.

**Comment by MizzleDK** [comment]
All right. Anyway, no, it's not supported at the moment, and probably won't be in the near future.

**Comment by da1nonly** [comment]
thanks for letting me know
