### ISSUE TITLE
Add option to bypass TV show details overview and go directly to seasons view

### ISSUE THREAD

**Issue by MizzleDK** [MizzleDK/Mizuu#533]

**Comment by budulinek** [comment]
Please please.... BIG ISSUE for me!

I need not only an option to bypass TV show details, but also an option to bypass the seasons list and an option to bypass the episode details. 

My small kids use Mizuu for their TV series and it is too complicated for them to go through all those TV show details, episode details etc. The first goal of Mizuu is to provide a quick (!) access to my movie and TV show collection. 

So far I have to:
click on a TV show -> scroll down to find a list of seasons -> click on a season (seasons have the same cover so kids can not distinguish between different seasons) -> scroll down and find an episode -> click on an episode -> click on that little arrow to play the episode


This is really extremely user unfriendly.

I would love to have an option in the settings that would allow me to bypass ALL show details / lists of seasons / episode details. I would love to:

click on a TV show -> scroll down and find an episode -> click on an episode to play it

Seasons and episodes could (should) be on one screen. I would love to have one long list of episodes in the right half of the screen. List of seasons would be in the left half of the screen. When you click on a season, the list of episodes would "jump" to the first episode of that season. When you click on the episode, it starts playing.


Right now I am downgrading back to "Mizuu beta" from mid-2013. The user interface was better back then...

**Comment by MizzleDK** [comment]
In all honesty, Mizuu isn't designed to be used by kids, and I'll never add just a list of all episodes that start playback when you press them. It's designed to be a media management software - not an application for kids.

If you want easy TV show playback, just use the play icon from the overview screen. It'll start the playback of the first episode you haven't watched.

**Comment by budulinek** [comment]
Media management software (database of detailed information about titles) or media center (visually appealing and easy access to movies and TV shows)? 

For me, detailed info of individual TV show episodes is really redundant. I was (maybe wrongly) expecting Mizuu to be a kind of Media center. 

A quotation from the Mizuu home page:
"Everything at your fingertips – as it should be."

Sorry, but individual episodes are not "at my fingertips". Yes, the last unwatched episode is at my fingerprints..... But it is too complicated to play specific episode from a TV series.

Honestly, I love Mizuu for its ability to grab covers, screenshots, backgrounds from internet databases. Another quotation from your home page:

"Your movie and TV show collection is presented as a grid of beautiful cover images. The tabbed interface provides an easy-to-use overview of your content."

YES! This is what I love. Grid of beautiful cover images, grid of screenshots from TV series. All movies and TV shows / episodes with correct names. Easy-to-use means easy to play (one or two clicks).

I do not expect you to ditch all your hard work in designing the screens with all those TV show details, episode details, actors etc. But at the same time I believe that the user should have the ability to choose the level of detail (do I prefer "click to play" or do I want to see all TV episode details)?

**Comment by MizzleDK** [comment]
No one ever said that it has to be either a media management software or a media center application. It can easily be both. What I did say is that it's not designed for kids.

You're the first person ever to have contacted me regarding problems with the user flow. I'm not saying that it means that others haven't thought of it, but they obviously haven't thought of it to be as much of an issue as to contact me about it. In other words: It's - at least - sufficient for almost all users.

Settings for stuff like the level of detail to display are incredibly counter-productive, and it makes user support and maintenance even harder. If you as an app developer need to have settings like that then you might as well confess to yourself that your solution doesn't work. If the user needs to actively do something in order to make it fit their purpose, then you're doing something wrong.

Like I said, I have no intention of adding a list of episodes, like you described. It has countless problems that are - in my humble opinion - worse than the issue you're pointing out.

**Comment by budulinek** [comment]
See my email...
