### ISSUE TITLE
Custom data not used for movie identification

### ISSUE THREAD

**Issue by platanoverde** [MizzleDK/Mizuu#536]
When device does not have Internet access, movies with local .nfo and custom art are not identified during a library update.  However, the custom data files are used for identification once an Internet connection is restored and a library update is performed.

It appears that the app is first checking for an Internet connection before looking at the custom data. The movie is left as unidentified if the Internet connection check fails.  On the other hand, a good Internet connection check is followed by the movie being identified using the local custom data (.nfo and art). 

Other details:
1) I have verified that “Ignore custom movie data files” is not checked in the settings.  

2) I have used very specific custom data and art to verify that the data used for identification is from the local files and not the Internet

3) Movies are on a SMB share

**Comment by MizzleDK** [comment]
It's implemented like that because there are a very limited number of use
cases where you're connected to a SMB server but don't have internet
access. It is possible to change it, but it's a low priority change.
Den 09/02/2015 05.31 skrev "platanoverde" <notifications@github.com>:

**Comment by platanoverde** [comment]
I understand that there are other fixes or enhancements with a higher priority. I think it’s fair to wait until you have a chance to address it. 

Changing the current method would be great for situations such as:

I have a travel router with smb access to movies on a USB thumbdrive. This setup is great for camping trips where Internet access is not available and the kids want to watch a movie. The router can also be used as a car media center to give passengers the ability to watch movies on long trips. Both of those scenarios don’t have Internet access available, but it’s not required for watching movies off of the smb served USB thumbdrive.

Thank you.

**Comment by platanoverde** [comment]
The movies were not being identified because my .nfo files only contained the Imdb "id" tags and not the "tmdbid" tags. Once I included the "tmdbid" tag, all movies were identified without Internet access.
