### ISSUE TITLE
filters using 'or' + 'not' instead of just 'and'

### ISSUE THREAD

**Issue by musicmonkey11** [MizzleDK/Mizuu#537]
so i can set the default view on kids phone to not include the R certification titles

The end result could give tickboxes next to the certifications. Each tick would allow that certification to show in search results, or ticking the box could strikeout the certifiaction and supress them from the results.

Currently I can't find a way of viewing the G, PG, PG-13 simultaneously.

this would also be useful in the release year filter -- less useful in the genres filter

thanks

**Comment by MizzleDK** [comment]
This would fall under the "advanced filtering" stuff that I mentioned in https://github.com/MizzleDK/Mizuu/issues/447.
