### ISSUE TITLE
Movies On SMB problems on OUYA

### ISSUE THREAD

**Issue by Rocamoya** [MizzleDK/Mizuu#540]
I have a minipc with duacore with ethernet adapter and the movies with 1080p and dts plays very good with Mizuu And Mx player.
But on my OUYA play slow like a network speed problem mx player pause all time trying to buffering. The ouya is connected with ethernet cable, the same as minipc.
Any idea?
Thanks

**Comment by MizzleDK** [comment]
It's generally not advisable to use SMB, as it introduces a massive amount of overhead and will limit your connection speed quite radically. Also, it depends a lot on the device itself - not the fact that it's connected by ethernet. There's nothing I can do other than ask you to use DLNA if possible.
