### ISSUE TITLE
Files not in TVDB

### ISSUE THREAD

**Issue by tojomo** [MizzleDK/Mizuu#542]
Files not in TVDB have a habit of crashing Mizuu. For example I have to manually identify Battlestar Galactica from the 80's version to the 2003 version. There is a improperly labeled special. It is labeled 3x00 instead of 0x??. I don't really care. However it stays in the old show (of which it is not) and if I try to move it Mizuu crashes. 

My suggestion is to create a improper files area to handle these. You would have Season 00 (extras), Season 1, 2, 3, and Unidentified Files. That way they are still grouped with their show, don't cause crashes and are able to be found and fixed more easily.

**Comment by MizzleDK** [comment]
This will be fixed in the reimagination of the app.
