### ISSUE TITLE
trakt - Social login

### ISSUE THREAD

**Issue by ghost** [MizzleDK/Mizuu#544]
Hello!

I use myGgoogle account to login into trakt account. At the moment, I can not log into the service, because the application doesn't provide social sign in.

**Comment by MizzleDK** [comment]
Hi Patrick,

The current version won't recieve any future updates. All work is being
done on the "reimagined" version of the app, as mentioned in the latest
blog post on www.mizuu.tv.
Den 12/03/2015 4.12 PM skrev "PatrikSelin" <notifications@github.com>:
