### ISSUE TITLE
Issues with TV episodes

### ISSUE THREAD

**Issue by mkinell** [MizzleDK/Mizuu#545]
I have serious issues with TV Episodes. For a lot of shows when clicking on an episodes the application crashes. It is the same with all the episodes of that show. When looking at Another show there might not be a problem at all. I just wish that there would be more consistency in the application. I do use the application on a Daily basis, so I do wish that I did not have these issues.

Thanks for a great application.
Mikael Kinell

**Comment by MizzleDK** [comment]
Hi!

I don't have any plans to provide future updates for the version you're using.

However, if you can be specific regarding the files that make it crash, I'll see if I can fix it in another upcoming project.

Cheers
Michell

**Comment by mkinell** [comment]
Hi

Hope you are doing well.

My issue is with some TV Shows. When clicking my way into a season I am not able to click on a single episode without crashing the app. It is Always all the episodes in a season. I can restart the app, but Always with the same result. I am not able to do anything about it.

Another suggestion that I have is that there are Always episodes that are never shown, neither under a show or as unidentified. That means that I am not able to look at them through the app.

Just to let you know the app is really important to me. I do have around 2000 Movies and 300 TV shows and it is impossible to keep track of Everything without your app. There is really nothing similar around in the market so thank you for the app.

Sincerely,
Mikael Kinell


25 mars 2015, Michell Bak <notifications@github.com> skrev:

**Comment by MizzleDK** [comment]
Hi again,

I need specific details about the TV show(s) in question. Filenames and folder structures, really.

**Comment by mkinell** [comment]
Hi

Here are some examples. Is the fact that it is numbers in the title that messes it up?
\\Wdmycloud\tv\123\100\The <file://\\Wdmycloud\tv\123\100\The> 100 S01E01.HDTV.XviD-AFG.avi

The 100 S01E02.HDTV.XviD-AFG.avi

\\Wdmycloud\tv\123\666 Park Avenue\666.Park.Avenue.S01E01.HDTV.XviD-AFG.avi <file://\\Wdmycloud\tv\123\666 Park Avenue\666.Park.Avenue.S01E01.HDTV.XviD-AFG.avi>

25 mars 2015, Michell Bak <notifications@github.com> skrev:

**Comment by MizzleDK** [comment]
I think it's the folder structure.

Any reason why the parent folder is called "123"? Also "100" isn't the title of the show. It should be "The 100" in the folder title.

**Comment by mkinell** [comment]
Thanks

I will give it a try!
Mikael


25 mars 2015, Michell Bak <notifications@github.com> skrev:
