### ISSUE TITLE
Pictures problem with new movies

### ISSUE THREAD

**Issue by glem78** [MizzleDK/Mizuu#546]
Hi,
Hope you are doing well.
Since 3 or 4 weeks, after each updates, new movies has a description but no pictures.
There is no error message.

Any idea ?

Cheers
Gilles

**Comment by MizzleDK** [comment]
Hi!

Something has deleted the images. I get reports of this happening from time to time, but there's nothing in Mizuu that would do that, so it must be a 3rd party application.

**Comment by glem78** [comment]
Thanks for your reply !

Maybe it's clean master ? I check that.

**Comment by glem78** [comment]
Hi,
after investigation, 
I uninstall clean master ==> same issue then 
I uninstall ad free and the problem is solved.

Thank you Michell
