### ISSUE TITLE
Artwork and Online Movies

### ISSUE THREAD

**Issue by intimategigs** [MizzleDK/Mizuu#547]
Just wondering if anyone else has an issues with artwork. This only happen recently and only with my android boxes/sticks. I use muzuu as my movie and tv media manager on all my televisions using android boxes and sticks via a samba network. I had no issues until around a month and half ago when I added movies and no artwork appeared. I reinstalled the app and none of the movies ot tv programs have any artwork or background. The files for mizuu are there but they have nothing in them. If you go to 'browse artwork' there is nothing but black rectangles. I don't have this on either of my android phones, they work great. I'm using an quad core amlogic S802 box via ethernet and two quad core amlogic S805 sticks via wifi. I've tried different roms incase it was an issue with that but nothing works. I also tried connecting the hard drive directly to the box in case it was a network issue but with the same results. Any feedback would be welcome as would really love to get it back working as not a fan of Kodi.

The 'Online Movies' also does not work now whether in 'Upcoming', In Theaters' or 'Popular'. 'Web Videos' also only plays audio, no picture.

**Comment by MizzleDK** [comment]
I believe this is due to problems with either TMDb or a change in the API URLs. I personally have no problems with artwork, but Online Movies did not work. I'm working on an update to Mizuu in my spare time and have removed Online Movies as it's really not a core feature of the app.
