### ISSUE TITLE
MPC Remote Support

### ISSUE THREAD

**Issue by SniperSL** [MizzleDK/Mizuu#552]
First of all, I love the App. I programmed something similar but not that advanced.

I have a suggestion for an extension. In my App you can push the play button or make a throw gesture in direction to the Remote screen than the install MPC https://mpc-hc.org/ (web interfaced enabled on the PC) start the movie from the network path. Also you can remote control the MPC.

	public static void playfile(String ip,String filepath) {
		

		// http://localhost:13579/browser.html?path=K:\anjelica\allfinegirls.anjelica.1080.mp4
		// http://localhost:13579/browser.html?path=\\sam\_HD_Movies_3_\World.War.Z.German.AC3.DL.1080p.BluRay.x264.mkv

		HttpClient httpclient = new DefaultHttpClient();
		
		String url = "192.168.1.213";
		try {
		        url = "http://"+ip+":"+DATEN.MCP_PORT+"/browser.html?path="+URLEncoder.encode(filepath, "UTF-8");
       
		    } catch (UnsupportedEncodingException e) {
		        e.printStackTrace();
		    }

			try {
		HttpPost httppost = new HttpPost(url);

	
			httpclient.execute(httppost);
			Log.d(tag, "pause");
		} catch (ClientProtocolException e) {
			
			
		} catch (IOException e) {
			
			
		}

**Comment by MizzleDK** [comment]
Mizuu is no longer being maintained.

**Comment by SniperSL** [comment]
OK, this is very sad
