### ISSUE TITLE
Unidentified Files are not shown for Samba files

### ISSUE THREAD

**Issue by aaronmclean1** [MizzleDK/Mizuu#555]
When I add movie files from a Samba share unknown movies are not added to the Unidentified Files list. If I add movie files from a folder called Action, then there is a movie called action. When I click on the Action movie it asks me which movie file I'd like to play. Then the unidentified movie files are shown. If I accidentally pick one of the movies and play it, I'll no longer be prompted to pick a movie and I am then not able to update the unknown movie info.

**Comment by MizzleDK** [comment]
A lot of stuff will happen with unidentified files, and this won't be relevant when it does, so I'll close it for now. Thanks for the heads up, though!
