### ISSUE TITLE
Keep original movie title

### ISSUE THREAD

**Issue by aaronmclean1** [MizzleDK/Mizuu#556]
When adding movie files, can we have the option to keep the original file name (without the file extension). This way the movies will sort correctly. It's miserable keeping track of the Marvel movies or what order the Harry Potter, Fast n Furious, and Hobbit movies should go in. If I can keep the original file name in Mizuu then I can control the order the movie icon is displayed on the screen.

**Comment by MizzleDK** [comment]
It's coming.
