### ISSUE TITLE
Mizuu on the Smart TV

### ISSUE THREAD

**Issue by mnazmul** [MizzleDK/Mizuu#557]
Hi Team, any plan to release Mizuu on the Smart TV? I have been using Mizuu last 3yrs and I am a fan of Mizuu. I would love to have it on the Smart TV as after having new Curve 3D Smart TV I am not using old Android media player. Will appreciate if someone come-up 1st version/beta & will be love to try....

**Comment by MizzleDK** [comment]
No, sorry.
