### ISSUE TITLE
Play from SMB path  

### ISSUE THREAD

**Issue by leocharrua** [MizzleDK/Mizuu#559]
I can't play videos from SMB share.

192.168.0.100 = Server IP (Windows 10)
192.168.0.102 = Local Mizuu IP

I try open the video with opera browser to see the error:

![playing_opera_error](https://cloud.githubusercontent.com/assets/1721923/16095094/76457c8e-3319-11e6-9ed5-05a56bee9fb0.jpg)

This is the movie information from Mizuu:

![movie_path](https://cloud.githubusercontent.com/assets/1721923/16095093/76410384-3319-11e6-8316-786f419eca21.jpg)

Notes: 
1) Mizuu get the movie information ok 
2) I can play the movie with ES file explorer (from the same network share)
3) I have other tablet with Mizuu working ok (same server, same share, same user, etc.)

Can you help me?

**Comment by MizzleDK** [comment]
The local SMB server is only accessible when you've started playback. Anyway, I'm not supporting Mizuu anymore. Sorry.

**Comment by leocharrua** [comment]
What you mean with "started playback"? Thanks.
PS:  It is a shame that you no longer supports Mizzu, is an excellent app in my opinion. What App substitute recommend? Thanks again

**Comment by leocharrua** [comment]
I love Mizuu. This is the end or someone else take the project? Thanks

**Comment by MizzleDK** [comment]
Please read this and disregard any newer posts on the blog:
http://mizuu.tv/this-is-it/

**Comment by leocharrua** [comment]
Good work with Jolly. Unfortunally my devices (tv-box and projector) have android 4 :(
Sorry, but I can't loose the hope to get mizuu working. Please, can you help me a little more?
I think the problem is that the routing to smb server is not working (port 50002). What part of the mizuu code, links the local ip with port 50002 to server IP? Thanks

**Comment by MizzleDK** [comment]
I don't think you quite understood the message of the blog post I linked to. Please don't continue this.
